// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package site

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "fmt"

func ContactPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div style=\"width: 100%; max-width: 64rem; margin: 0 auto; padding: 2rem 1rem;\"><h1 style=\"font-size: 2.25rem; font-weight: 700; margin-bottom: 2rem;\">Contact Us</h1><div style=\"display: grid; grid-template-columns: 1fr; gap: 2rem;\"><div><h2 style=\"font-size: 1.5rem; font-weight: 600; margin-bottom: 1rem;\">Get in Touch</h2><p style=\"color: var(--text-secondary); margin-bottom: 1.5rem;\">We'd love to hear from you. Whether you have questions about Ocuroot,  need support, or want to discuss how we can help with your release orchestration needs.</p><div style=\"margin-bottom: 1.5rem;\"><h3 style=\"font-size: 1.125rem; font-weight: 500; margin-bottom: 0.5rem;\">Email</h3><a href=\"mailto:contact@ocuroot.com\" style=\"color: var(--link-color); text-decoration: none;\" onmouseover=\"this.style.textDecoration='underline'\" onmouseout=\"this.style.textDecoration='none'\">contact@ocuroot.com</a></div></div><div><h2 style=\"font-size: 1.5rem; font-weight: 600; margin-bottom: 1rem;\">Follow Us</h2><p style=\"color: var(--text-secondary); margin-bottom: 1.5rem;\">Stay updated with the latest news, features, and insights from the Ocuroot team.</p><ul style=\"list-style: none; padding: 0; margin: 0;\"><li style=\"display: flex; align-items: center; margin-bottom: 0.75rem;\"><img src=\"/icons/bluesky.svg\" alt=\"Bluesky\" style=\"width: 1.25rem; height: 1.25rem; margin-right: 0.5rem; filter: brightness(0) saturate(100%) invert(10%) sepia(0%) saturate(0%) hue-rotate(0deg) brightness(100%) contrast(100%);\"> <a href=\"https://bsky.app/profile/ocuroot.com\" target=\"_blank\" rel=\"noopener noreferrer\" style=\"color: var(--link-color); text-decoration: none;\" onmouseover=\"this.style.textDecoration='underline'\" onmouseout=\"this.style.textDecoration='none'\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprint("@ocuroot.com"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `site/contact.templ`, Line: 39, Col: 191}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</a></li><li style=\"display: flex; align-items: center; margin-bottom: 0.75rem;\"><img src=\"/icons/github.svg\" alt=\"GitHub\" style=\"width: 1.25rem; height: 1.25rem; margin-right: 0.5rem; filter: brightness(0) saturate(100%) invert(10%) sepia(0%) saturate(0%) hue-rotate(0deg) brightness(100%) contrast(100%);\"> <a href=\"https://github.com/ocuroot/ocuroot\" target=\"_blank\" rel=\"noopener noreferrer\" style=\"color: var(--link-color); text-decoration: none;\" onmouseover=\"this.style.textDecoration='underline'\" onmouseout=\"this.style.textDecoration='none'\">ocuroot/ocuroot</a></li><li style=\"display: flex; align-items: center; margin-bottom: 0.75rem;\"><img src=\"/icons/linkedin.svg\" alt=\"LinkedIn\" style=\"width: 1.25rem; height: 1.25rem; margin-right: 0.5rem; filter: brightness(0) saturate(100%) invert(10%) sepia(0%) saturate(0%) hue-rotate(0deg) brightness(100%) contrast(100%);\"> <a href=\"https://linkedin.com/company/ocuroot\" target=\"_blank\" rel=\"noopener noreferrer\" style=\"color: var(--link-color); text-decoration: none;\" onmouseover=\"this.style.textDecoration='underline'\" onmouseout=\"this.style.textDecoration='none'\">company/ocuroot</a></li></ul></div></div><style>\n\t\t\t\t@media (min-width: 768px) {\n\t\t\t\t\t.contact-grid {\n\t\t\t\t\t\tgrid-template-columns: 1fr 1fr;\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t</style><script>\n\t\t\t\tdocument.addEventListener('DOMContentLoaded', function() {\n\t\t\t\t\tconst grid = document.querySelector('[style*=\"display: grid\"]');\n\t\t\t\t\tif (grid && window.innerWidth >= 768) {\n\t\t\t\t\t\tgrid.style.gridTemplateColumns = '1fr 1fr';\n\t\t\t\t\t}\n\t\t\t\t});\n\t\t\t</script></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = root(RootProps{
			Title: "Contact Us",
			Path:  "/contact",
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
