// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.920
package site

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/ocuroot/ui/components"
	"github.com/ocuroot/ui/components/navbar"
	"github.com/ocuroot/ui/js"
)

func root(path string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = navbar.Navbar(navbar.NavbarConfig{
				BrandName: "Ocuroot",
				BrandURL:  "/",
				LogoURL:   "/static/logo.svg",
				Items: []navbar.NavItem{
					navbar.NavLink{
						Name:   "About",
						URL:    "/",
						Active: path == "/",
					},
					navbar.NavDropdown{
						ID:   "solutions",
						Name: "Solutions",
						Items: []navbar.DropdownItem{
							{Name: "Release faster", URL: "/solutions/productivity-satisfaction"},
							{Name: "Reduce cloud spend", URL: "/solutions/cost-management"},
							{Name: "Simplify audits & compliance", URL: "/solutions/security-compliance"},
							{Name: "Manage your growing footprint", URL: "/solutions/technical-agility"},
						},
					},
					navbar.NavLink{
						Name:   "Blog",
						URL:    "/blog",
						Active: path == "/blog",
					},
					navbar.NavLink{
						Name:   "Docs",
						URL:    "/docs",
						Active: path == "/docs",
					},
					navbar.NavLink{
						Name:   "Book a Demo",
						URL:    "/demo",
						Active: path == "/demo",
					},
					navbar.NavComponent{
						Component: SocialButtons(),
					},
				},
				ShowThemeToggle: true,
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = Footer().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = js.UnifiedJSScript().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = components.Body().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func SocialButtons() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<style>\n\t\t.social-buttons {\n\t\t\tdisplay: flex;\n\t\t\talign-items: center;\n\t\t\tjustify-content: space-between;\n\t\t\tgap: 1rem;\n\t\t\tpadding: 0.75rem 1rem;\n\t\t}\n\t\t.social-button {\n\t\t\tdisplay: inline-flex;\n\t\t\talign-items: center;\n\t\t\tgap: 0.5rem;\n\t\t\ttext-decoration: none;\n\t\t\tcolor: white;\n\t\t\ttransition: color 0.2s ease-in-out;\n\t\t}\n\t\t.social-button:hover {\n\t\t\tcolor: #b3b3b3;\n\t\t}\n\t\t.social-button img {\n\t\t\twidth: 1.5rem;\n\t\t\theight: 1.5rem;\n\t\t}\n\t</style><div class=\"social-buttons\"><a href=\"https://linkedin.com/company/ocuroot\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"social-button\" data-vmtrc=\"SocialClick\" data-vmtrc-platform=\"LinkedIn\"><img src=\"/icons/linkedin.svg\" alt=\"LinkedIn\"></a> <a href=\"https://bsky.app/profile/ocuroot.com\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"social-button\" data-vmtrc=\"SocialClick\" data-vmtrc-platform=\"Bluesky\"><img src=\"/icons/bluesky.svg\" alt=\"Bluesky\"></a> <a href=\"https://github.com/ocuroot/ocuroot\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"social-button\" data-vmtrc=\"SocialClick\" data-vmtrc-platform=\"GitHub\"><img src=\"/icons/github.svg\" alt=\"GitHub\"></a></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
